### ISSUE TITLE
F and inhg conversion

### ISSUE THREAD

**Issue by psu1989** [awitwicki/MMM-BME280#2]
Any plans to add conversion to F and inhg?

Thanks,

**Comment by psu1989** [comment]
My son and I figured out 1 solution:

```
         case 0:
		val = this.temperature
		if (!isNaN(+val))
		val = Math.round(val * 9.0 / 5.0 + 32.0);
		icon_img = "temperature-high";
		sufix = "°F";
		break;
	case 1:
		val = this.humidity;
		icon_img = "tint";
		sufix = "%";
		break;
	case 2:
		val = this.pressure
		if (!isNaN(+val))
		val = Math.round(val * 0.02952998751*100)/100;
		icon_img = "tachometer-alt";
		sufix = "''";

```

**Comment by awitwicki** [comment]
Hi, solved in last [commits](https://github.com/awitwicki/MMM-BME280/commit/f38f95d08ba72dff0e3da06de92079af75cf0c98).

**Comment by psu1989** [comment]
> Hi, solved in last [commits](https://github.com/awitwicki/MMM-BME280/commit/f38f95d08ba72dff0e3da06de92079af75cf0c98).

Looks ok. Can you round barometric pressure to two decimal points  (29.46 not 29)?

**Comment by awitwicki** [comment]
> > Hi, solved in last [commits](https://github.com/awitwicki/MMM-BME280/commit/f38f95d08ba72dff0e3da06de92079af75cf0c98).
> 
> Looks ok. Can you round barometric pressure to two decimal points (29.46 not 29)?

Done. 
Now I  understand why You proposed that way for calculating pressure.

**Comment by psu1989** [comment]
not sure your formula is correct.  The sensor is reporting 1003.6 hPa.
Yours converts that to 30.41 inHg but i think it should be  29.64
this works:   
val = Math.round(this.pressure * 10000 / 3386) / 100;

**Comment by awitwicki** [comment]
The problem was in "," in formula:
old code `val = Math.round(this.pressure * 100 / 33,864) / 100;`
new code `val = Math.round(this.pressure * 100 / 33.864) / 100;`

In old code javascript was interpreting 33,864 as 2 variables (33 and 864) and returned 33 as 1th array element. So formula was working the next way:
 `val = Math.round(this.pressure * 100 / 33) / 100;`

Now it fixed with new commit.

**Comment by psu1989** [comment]
perfect!
